// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entity "CareerCenter/domain/entity"
	filter "CareerCenter/domain/entity/filter"
	context "context"

	mock "github.com/stretchr/testify/mock"

	valueobject "CareerCenter/domain/valueobject"
)

// RepoJobs is an autogenerated mock type for the RepoJobs type
type RepoJobs struct {
	mock.Mock
}

// CreateJob provides a mock function with given fields: ctx, data
func (_m *RepoJobs) CreateJob(ctx context.Context, data *entity.Jobs) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Jobs) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteJobById provides a mock function with given fields: ctx, id
func (_m *RepoJobs) DeleteJobById(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetJobByCompanyId provides a mock function with given fields: ctx, id
func (_m *RepoJobs) GetJobByCompanyId(ctx context.Context, id string) ([]*entity.JobsDTO, error) {
	ret := _m.Called(ctx, id)

	var r0 []*entity.JobsDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.JobsDTO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.JobsDTO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.JobsDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJobById provides a mock function with given fields: ctx, id
func (_m *RepoJobs) GetJobById(ctx context.Context, id string) (*entity.JobsDTO, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.JobsDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.JobsDTO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.JobsDTO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.JobsDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListJobs provides a mock function with given fields: ctx, typeSearch, f
func (_m *RepoJobs) GetListJobs(ctx context.Context, typeSearch *valueobject.TypeSearch, f *filter.Filter) ([]*entity.JobsDTO, error) {
	ret := _m.Called(ctx, typeSearch, f)

	var r0 []*entity.JobsDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *valueobject.TypeSearch, *filter.Filter) ([]*entity.JobsDTO, error)); ok {
		return rf(ctx, typeSearch, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *valueobject.TypeSearch, *filter.Filter) []*entity.JobsDTO); ok {
		r0 = rf(ctx, typeSearch, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.JobsDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *valueobject.TypeSearch, *filter.Filter) error); ok {
		r1 = rf(ctx, typeSearch, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateJobById provides a mock function with given fields: ctx, data
func (_m *RepoJobs) UpdateJobById(ctx context.Context, data *entity.Jobs) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Jobs) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepoJobs interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepoJobs creates a new instance of RepoJobs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepoJobs(t mockConstructorTestingTNewRepoJobs) *RepoJobs {
	mock := &RepoJobs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
