// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	profile "CareerCenter/domain/entity/profile"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UseCaseProfile is an autogenerated mock type for the UseCaseProfile type
type UseCaseProfile struct {
	mock.Mock
}

// GetProfileByEmail provides a mock function with given fields: ctx, email
func (_m *UseCaseProfile) GetProfileByEmail(ctx context.Context, email string) (*profile.ProfileUserDTO, error) {
	ret := _m.Called(ctx, email)

	var r0 *profile.ProfileUserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*profile.ProfileUserDTO, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *profile.ProfileUserDTO); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.ProfileUserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: ctx, email, data
func (_m *UseCaseProfile) UpdateProfile(ctx context.Context, email string, data *profile.ProfileUserDTO) error {
	ret := _m.Called(ctx, email, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *profile.ProfileUserDTO) error); ok {
		r0 = rf(ctx, email, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUseCaseProfile interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCaseProfile creates a new instance of UseCaseProfile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCaseProfile(t mockConstructorTestingTNewUseCaseProfile) *UseCaseProfile {
	mock := &UseCaseProfile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
