// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entity "CareerCenter/domain/entity"
	filter "CareerCenter/domain/entity/filter"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UseCaseCompany is an autogenerated mock type for the UseCaseCompany type
type UseCaseCompany struct {
	mock.Mock
}

// GetCompanyById provides a mock function with given fields: ctx, id
func (_m *UseCaseCompany) GetCompanyById(ctx context.Context, id string) (*entity.CompanyDTO, []*entity.JobsDTO, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.CompanyDTO
	var r1 []*entity.JobsDTO
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.CompanyDTO, []*entity.JobsDTO, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.CompanyDTO); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CompanyDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) []*entity.JobsDTO); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*entity.JobsDTO)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetListCompany provides a mock function with given fields: ctx, f
func (_m *UseCaseCompany) GetListCompany(ctx context.Context, f *filter.FilterDTO) ([]*entity.CompanyDTO, error) {
	ret := _m.Called(ctx, f)

	var r0 []*entity.CompanyDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *filter.FilterDTO) ([]*entity.CompanyDTO, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *filter.FilterDTO) []*entity.CompanyDTO); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.CompanyDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *filter.FilterDTO) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCaseCompany interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCaseCompany creates a new instance of UseCaseCompany. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCaseCompany(t mockConstructorTestingTNewUseCaseCompany) *UseCaseCompany {
	mock := &UseCaseCompany{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
